### ISSUE TITLE
Make compatible with twin.macro

### ISSUE THREAD

**Issue by michael-pomelo** [tailwindlabs/prettier-plugin-tailwindcss#55] opened 2022-02-10 15:08 UTC
First off, thanks for putting this plugin out there! I think it's awesome.

It would be fantastic if this had the ability to work with [twin.macro](https://github.com/ben-rogerson/twin.macro).  That is how we are using tailwind in our project but this plugin doesn't seem to work with it.

It would be perfect if we can pass in a custom regex to apply the formatting to, just like how twin.macro is configured to work with the official Tailwind VSCode plugin. https://github.com/ben-rogerson/twin.macro/discussions/227

**Comment by bradlc** [comment] 2022-02-14 11:06
Hey @michael-pomelo. I'm going to close this as a duplicate of #6 as that is essentially the same idea: sorting classes outside of attributes/in custom places

**Closed by bradlc** 2022-02-14 11:06 UTC
