### ISSUE TITLE
Excess whitespaces should be removed

### ISSUE THREAD

**Issue by daalfox** [tailwindlabs/prettier-plugin-tailwindcss#238] opened 2023-12-29 08:42 UTC
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.5.10

**What version of Tailwind CSS are you using?**

v3.3.3

**What version of Node.js are you using?**

v21.4.0

**What package manager are you using?**

npm

**What operating system are you using?**

Arch Linux

**Reproduction URL**

Please remove this section. Who would want to create a public repo as a reproduction for every small issue he/she open? People will just avoid opening issues because of this extra work and your software will have bugs that could be fixed with a simple title+description issue.

**Describe your issue**

prettier-plugin-tailwindcss doesn't remove excess white spaces between classes or trailing whitespaces

**Comment by adamwathan** [comment] 2023-12-29 14:53
Duplicate of https://github.com/tailwindlabs/tailwindcss/discussions/7560

**Closed by adamwathan** 2023-12-29 14:53 UTC
