### ISSUE TITLE
Could we trim the sides?

### ISSUE THREAD

**Issue by jvzaniolo** [tailwindlabs/prettier-plugin-tailwindcss#22] opened 2022-01-26 04:06 UTC
```html
// before
<body className=" text-white bg-slate-900   "></body>

// after formatting
<body className=" bg-slate-900 text-white   "></body>

// expected behavior
<body className="bg-slate-900 text-white"></body> // <-- trim
```

**Comment by MichaelDeBoey** [comment] 2022-01-26 11:48
Duplicate of #12

**Comment by reinink** [comment] 2022-01-26 12:44
Closing this in favor of #12

**Closed by reinink** 2022-01-26 12:44 UTC
