### ISSUE TITLE
seems to have no effect on class lists in template literals

### ISSUE THREAD

**Issue by DanielFGray** [tailwindlabs/prettier-plugin-tailwindcss#32] opened 2022-01-30 00:01 UTC
as an example:
```js
<div
  className={`
    flex
    flex-col
    justify-between
    flex-1
    p-6
    bg-gradient-to-br
    bg-white
    from-white
    to-gray-200
    dark:bg-gray-800
    dark:from-gray-800
    dark:to-gray-900
    dark:text-gray-50
    ${className}
  `}
>
```
plugin seems to not operate on these strings, flattening them into a single line seems to not have any effect either

I have also tried randomly shuffling the class list to see if they were already sorted

**Comment by bradlc** [comment] 2022-02-07 16:12
Hey @DanielFGray. The plugin [does](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/blob/main/tests/test.js#L69) sort template literals. Please can you provide a reproduction repository?

**Comment by bradlc** [comment] 2022-02-21 13:15
I'm going to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction — a GitHub repository where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get across all of our projects. Hope that's understandable!

**Closed by bradlc** 2022-02-21 13:15 UTC

**Comment by sebastienbarre** [comment] 2022-03-25 16:02
Hi @bradlc 

I just gave this plugin a shot, and I'm seeing a similar behavior:

```jsx
export const Hello = () => {
  const classNames = 'pt-2 p-4';
  return <div className="pt-2 p-4" />;
};
```
Notice how the second list of classes is fixed when I run prettier, but not the one in the variable:
```
$ ./node_modules/.bin/prettier Hello.jsx
export const Hello = () => {
  const classNames = 'pt-2 p-4';
  return <div className="p-4 pt-2" />;
};
```

Most of my components are build that way, here is a slightly less contrived example:
```jsx
import clsx from 'clsx';

export const Hello = ({needPadding, needColors, className}) => {
  const classNames = clsx({
    'pt-2 p-4': needPadding,
    'bg-blue-700': needColors,
  }, className);
  return <div className={classNames} />;
};
```
In which case, again, `'pt-2 p-4'` is not fixed either...

Thank you for the hard work

**Comment by steveoh** [comment] 2022-06-21 20:18
Was the above opened as a new issue?

**Comment by quantuminformation** [comment] 2022-12-05 17:53
doesn't work here:

```js
import { ParentComponent, onCleanup } from 'solid-js';

//types of button
export enum ButtonType {
  Pagination,
  Action,
}

//todo decide common things like font size and font weight from the DS
export const O_Button: ParentComponent<{ buttonType: ButtonType }> = (props) => {
  const buttonType = props.buttonType;
  const className =
    buttonType === ButtonType.Pagination
      ? ' px-4 py-[10px] text-sm font-medium hover:border-primary-300 hover:bg-primary-50 active:border-primary-300 active:bg-primary-50 rounded-none border-[0.5px] hover:border max-[425px]:px-[.5rem]'
      : '';

  return <button class={` ${className}`}>{props.children}</button>;
};

```

**Comment by quantuminformation** [comment] 2022-12-05 17:55
I do it like this, because there will be a lot of dynamic building up of strings
