### ISSUE TITLE
Error: Cannot find module 'prettier-plugin-tailwindcss'

### ISSUE THREAD

**Issue by Chen-913** [tailwindlabs/prettier-plugin-tailwindcss#110] opened 2022-12-22 03:38 UTC
**What version of `prettier-plugin-tailwindcss` are you using?**

^0.2.1

**What version of Tailwind CSS are you using?**

^3.2.4

**What version of Node.js are you using?**

v14.19.3

**What package manager are you using?**

pnpm

**What operating system are you using?**

Windows

**Reproduction URL**

A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.

https://github.com/Chen-913/react-demo.git

**Describe your issue**

I tried to use this plug-in so that prettier could help me sort the class class names, but when I saved it in App.tsx, it showed that the module could not be found in the output bar

![image](https://user-images.githubusercontent.com/72293244/209050282-50af5d34-9afa-498f-a351-0faa7f6bd871.png)

**Comment by Chen-913** [comment] 2022-12-22 03:40
By the way, I installed the prettier plug-in in vscode, and it's the latest.

**Comment by adamwathan** [comment] 2022-12-22 14:05
Hey! Just cloned the repo and installed the dependencies with pnpm (based on the fact that you have a `pnpm-lock.yaml` file) and the plugin is working for me with no errors so I'm guessing this is configuration or caching thing.

I would try deleting `node_modules` and reinstalling your dependencies and manually verifying that the `pretter-plugin-tailwindcss` module is actually present since the error is saying it can't find it. Unfortunately there isn't really any action we can take on our end here since I can't reproduce the issue so I'm going to close this — the best places to get help with these types of troubleshooting problems are our [discussion forums](https://github.com/tailwindlabs/tailwindcss/discussions) or our [Discord server](https://tailwindcss.com/discord).

Hope that at least gets you pointed in the right direction!

**Closed by adamwathan** 2022-12-22 14:05 UTC
