### ISSUE TITLE
Support for tailwindCSS class matching

### ISSUE THREAD

**Issue by TatisLois** [tailwindlabs/prettier-plugin-tailwindcss#37] opened 2022-02-03 16:34 UTC
So happy about this plugin! 

I'm not sure what the best way to make a feature request or contribute back to the project but something that could help tailwind users is if the plugin supported class matching. This would allow support for class sorting for applications using tailwind in all sorts of different ways.

For example a project that i'm on is built on react native (mobile+web) and we use a library called [tailwind react native classnames](https://github.com/jaredh159/tailwind-react-native-classnames) to use tailwind in our app.

For this library instead of using class or className it uses `tw` and `tw.style`. One issue we noticed early on was tailwind intellisense support did not work out of the box but by adding it to our `tailwindCSS.experimental.classRegex` and `tailwindCSS.classAttributes` in vs code settings file it started to work.

Would a feature like this make sense? I'm not as familiar with writing plugins but can take a try at it if it makes sense and am pointed in the right direction.

Thank you!

**Comment by bradlc** [comment] 2022-02-04 16:48
Duplicate of #6

**Closed by bradlc** 2022-02-04 16:48 UTC

**Comment by skoob13** [comment] 2023-01-10 10:41
@bradlc I have a similar problem using [nativewind](https://github.com/marklawlor/nativewind). Nativewind allows to style react-native components with two props: `className` and `tw`. If I add `tw` in the array on [this line](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/blob/main/src/index.js#L472), the plugin formats `tw` props. It might be worth to allow formatting of custom attributes, but I have no problems refactoring to `className`.
